spring.application.name=airhermes

spring.messages.encoding=UTF-8

#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.cache=false

#server.port = 8080
#server.servlet.session.timeout=5
spring.session.timeout.seconds=300

#spring.mvc.static-path-pattern=/**
#spring.resources.static-locations=

#spring.mvc.view.prefix: /WEB-INF/jsp/
#spring.mvc.view.suffix: .jsp

spring.thymeleaf.enabled=true

#server.servlet.contextPath=/AirHermes
server.servlet.contextPath=/airhermes

#spring.jackson.time-zone=Europe/Belgrade
#spring.datasource.time-zone=UTC

#-Duser.timezone=UTC

#spring.session.jdbc.initialize-schema=always

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/airhermes?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
